"use client"

import { Card, CardContent } from '@/components/ui/card';
import { ListTodo, Construction, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export default function TasksPage() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[70vh] space-y-8 animate-in fade-in duration-700">
      <div className="text-center space-y-4">
        <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-3xl bg-primary/10 text-primary shadow-inner">
          <ListTodo className="h-10 w-10" />
        </div>
        <div className="space-y-2">
          <h2 className="text-4xl font-black tracking-tight text-primary">Task Management</h2>
          <p className="text-muted-foreground text-lg max-w-md mx-auto">
            We're building a centralized task tracking system for the Dhaka L2 team.
          </p>
        </div>
      </div>

      <Card className="w-full max-w-2xl border-dashed border-2 bg-muted/20">
        <CardContent className="flex flex-col items-center py-12 space-y-6">
          <div className="flex items-center gap-3 px-4 py-2 bg-amber-100 text-amber-700 rounded-full text-xs font-bold uppercase tracking-wider border border-amber-200">
            <Construction className="h-4 w-4" />
            Module Under Construction
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full px-4">
            <div className="p-4 rounded-xl bg-background border shadow-sm space-y-2">
              <div className="h-8 w-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center">
                <span className="font-bold">01</span>
              </div>
              <h4 className="font-bold text-sm">Sprint Sync</h4>
              <p className="text-xs text-muted-foreground">Automated task syncing from GitHub project milestones.</p>
            </div>
            <div className="p-4 rounded-xl bg-background border shadow-sm space-y-2">
              <div className="h-8 w-8 rounded-lg bg-purple-50 text-purple-600 flex items-center justify-center">
                <span className="font-bold">02</span>
              </div>
              <h4 className="font-bold text-sm">L2 Queue</h4>
              <p className="text-xs text-muted-foreground">Prioritized queue for tickets needing immediate observation.</p>
            </div>
            <div className="p-4 rounded-xl bg-background border shadow-sm space-y-2">
              <div className="h-8 w-8 rounded-lg bg-green-50 text-green-600 flex items-center justify-center">
                <span className="font-bold">03</span>
              </div>
              <h4 className="font-bold text-sm">Reporting</h4>
              <p className="text-xs text-muted-foreground">Weekly productivity reports generated by enterprise AI.</p>
            </div>
          </div>

          <Button asChild variant="outline" className="mt-8 group">
            <Link href="/dashboard">
              Return to Dashboard <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
            </Link>
          </Button>
        </CardContent>
      </Card>
      
      <p className="text-[10px] text-muted-foreground uppercase tracking-[0.2em] font-bold">
        Expected Release: Q2 2024
      </p>
    </div>
  );
}
